### ISSUE TITLE
Need some checksum 

### ISSUE THREAD

**Issue by pletzer** [sswolfson/UoA00539#4]
Hi @sswolfson:

Can we add some checksums at the end of the computation so we don't have to open the excel file to check the results? Maybe print sum(resultMat).

**Comment by sswolfson** [comment]
Yes. Working on one that will make sure all measures were generated.

I have an easy change to suppress the Matlab warnings.

Steve

Sent from my iPhone

On Dec 19, 2018, at 1:35 PM, Alex Pletzer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @sswolfson<https://github.com/sswolfson>:

Can we add some checksums at the end of the computation so we don't have to open the excel file to check the results? Maybe print sum(resultMat).

**Comment by sswolfson** [comment]
Added checksum to RS script.
